Added Inactivity Penalty tests & GRACE_PERIOD constant
razor-network/contracts pull request #115
Opened 2021-04-28 15:07 UTC by doctoc

Description : 
GRACE_PERIOD constant added in constants.js
Defined as the max allowed inactive epochs for which there is no inactivity penalty.

Added Inactivity Penalty tests in StakeManager.js
1. Staker should be penalised when no. of inactive epochs > GRACE_PERIOD
2. Staker should not be penalised when no. of inactive epochs <= GRACE_PERIOD

2021-04-30 14:54 UTC, abhishekvispute commented
Hey @doctoc 
As we merged https://github.com/razor-network/contracts/pull/99 
There are some conflicts 
Please rebase and resolve them

2021-05-05 08:26 UTC, abhishekvispute submitted a review, later dismissed
LGTM
@SkandaBhat Please do Squash and Merge

2021-05-05 08:38 UTC, dev1644 requested changes
Hi @doctoc , also run `npm run lint:fix`, then I think we are good tgo go.

2021-05-05 08:50 UTC, SkandaBhat commented on test/StakeManager.js
> +    it('should penalize staker if number of inactive epochs > grace_period' , async function(){
+1

2021-05-05 09:51 UTC, doctoc commented on test/StakeManager.js
> +    it('should penalize staker if number of inactive epochs > grace_period' , async function(){
Done . Please review

2021-05-05 10:19 UTC, dev1644 approved these changes

2021-05-05 11:22 UTC, abhishekvispute approved these changes

2021-05-06 07:24 UTC, merged