Added restriction to Schelling Coin add Minter and Remove Minter
razor-network/contracts pull request #150
Opened 2021-06-09 05:17 UTC by adi44

Currently anyone can become minter or remove itself as minter which might lead to some security issues. Hence in order to resolve this I have added a restriction that only owner can add the Minter and remove the minter.

2021-06-09 06:17 UTC, abhishekvispute requested changes

2021-06-09 06:17 UTC, abhishekvispute commented on contracts/SchellingCoin.sol
> +
Please remove these extra lines across the code - add/remove minter
Else LGTM

2021-06-09 08:47 UTC, abhishekvispute approved these changes
LGTM

2021-06-10 05:44 UTC, SkandaBhat approved these changes

2021-06-10 05:44 UTC, merged