Block Proposal Bug Fix
razor-network/contracts pull request #347
Opened 2021-08-19 11:55 UTC by SamAg19

Fixes #105 
Details of active assets in #297

2021-08-20 09:30 UTC, hrishikeshio commented
Please add gas usage report. before and after.

2021-08-20 17:18 UTC, SkandaBhat requested changes

2021-08-20 17:18 UTC, SkandaBhat commented on contracts/Core/AssetManager.sol
> +        numActiveAssets++;
We should keep the increment uniform, in line 132 and 133 for better readability.

2021-08-23 06:44 UTC, SamAg19 commented on contracts/Core/Parameters.sol
> +        uint8 state = uint8(((block.number) / (epochLength / NUM_STATES)) % (NUM_STATES));
That was done in StateManager.sol. This is in Parameters.sol

2021-08-23 06:45 UTC, SamAg19 commented on contracts/Core/AssetManager.sol
> +    //event CollectionReported(
FulfillAsset will be reintroduced so i thought better to comment it

2021-08-23 06:45 UTC, SamAg19 commented on contracts/Core/AssetManager.sol
> +    //event JobReported(
Even if fulfillAsset returns, we arent reporting for jobs anymore. Hence, removed

2021-08-23 07:02 UTC, SamAg19 commented
> Please add gas usage report. before and after.
@hrishikeshio @abhishekvispute @SkandaBhat 
Before
<pre>On ethereum network. It will take take following cost for tx
Commit: $ <font color="#C4A000">21.95524854768</font>
reveal: $ <font color="#C4A000">34.9343652504</font>
propose: $ <font color="#C4A000">22.4826230328</font>
cost per epoch: $ <font color="#C4A000">66.92049461328</font>
cost per day if epoch = 10min: $ <font color="#C4A000">9636.55122431232</font>
cost per week if epoch = 10min: $ <font color="#C4A000">67455.85857018623</font>
cost per month if epoch = 10min: $ <font color="#C4A000">289096.5367293696</font>
cost per day if epoch = 1 hour: $ <font color="#C4A000">1606.09187071872</font>
cost per week if epoch = 1 hour: $ <font color="#C4A000">11242.64309503104</font>
cost per month if epoch = 1 hour: $ <font color="#C4A000">48182.7561215616</font>
========================================================
On Polygon network. It will take take following cost for tx
Commit: $ <font color="#C4A000">0.0003944551659025628</font>
reveal: $ <font color="#C4A000">0.000627642215510395</font>
propose: $ <font color="#C4A000">0.0004039301481405922</font>
cost per epoch: $ <font color="#C4A000">0.0012023154621837472</font>
cost per day if epoch = 10min: $ <font color="#C4A000">0.1731334265544596</font>
cost per week if epoch = 10min: $ <font color="#C4A000">1.2119339858812173</font>
cost per month if epoch = 10min: $ <font color="#C4A000">5.194002796633788</font>
cost per day if epoch = 1 hour: $ <font color="#C4A000">0.028855571092409934</font>
cost per week if epoch = 1 hour: $ <font color="#C4A000">0.20198899764686953</font>
cost per month if epoch = 1 hour: $ <font color="#C4A000">0.865667132772298</font>
On Arbitrum network. It will take take following cost for tx (Not real time)
Commit: $ <font color="#C4A000">0.235234805868</font>
reveal: $ <font color="#C4A000">0.37429677054000005</font>
propose: $ <font color="#C4A000">0.24088524678</font>
cost per epoch: $ <font color="#C4A000">0.7170052994280001</font>
cost per day if epoch = 10min: $ <font color="#C4A000">103.24876311763201</font>
cost per week if epoch = 10min: $ <font color="#C4A000">722.741341823424</font>
cost per month if epoch = 10min: $ <font color="#C4A000">3097.46289352896</font>
cost per day if epoch = 1 hour: $ <font color="#C4A000">17.208127186272</font>
cost per week if epoch = 1 hour: $ <font color="#C4A000">120.456890303904</font>
cost per month if epoch = 1 hour: $ <font color="#C4A000">516.24381558816</font>
========================================================
On Avalanche network. It will take take following cost for tx
Commit: $ <font color="#C4A000">1.74860171325</font>
reveal: $ <font color="#C4A000">2.78230924125</font>
propose: $ <font color="#C4A000">1.79060387625</font>
cost per epoch: $ <font color="#C4A000">5.3298094657499995</font>
cost per day if epoch = 10min: $ <font color="#C4A000">767.492563068</font>
cost per week if epoch = 10min: $ <font color="#C4A000">5372.447941476</font>
cost per month if epoch = 10min: $ <font color="#C4A000">23024.776892039998</font>
cost per day if epoch = 1 hour: $ <font color="#C4A000">127.91542717799999</font>
cost per week if epoch = 1 hour: $ <font color="#C4A000">895.4079902459999</font>
cost per month if epoch = 1 hour: $ <font color="#C4A000">3837.4628153399995</font>
========================================================
On xDAI network. It will take take following cost for tx (Not real time)
Commit: $ <font color="#C4A000">0.000157033</font>
reveal: $ <font color="#C4A000">0.000249865</font>
propose: $ <font color="#C4A000">0.000160805</font>
cost per epoch: $ <font color="#C4A000">0.00047864299999999995</font>
cost per day if epoch = 10min: $ <font color="#C4A000">0.06892459199999999</font>
cost per week if epoch = 10min: $ <font color="#C4A000">0.48247214399999994</font>
cost per month if epoch = 10min: $ <font color="#C4A000">2.06773776</font>
cost per day if epoch = 1 hour: $ <font color="#C4A000">0.011487431999999999</font>
cost per week if epoch = 1 hour: $ <font color="#C4A000">0.080412024</font>
cost per month if epoch = 1 hour: $ <font color="#C4A000">0.34462296</font></pre>

After
<pre>On ethereum network. It will take take following cost for tx
Commit: $ <font color="#C4A000">23.167998115240003</font>
reveal: $ <font color="#C4A000">36.970162970400004</font>
propose: $ <font color="#C4A000">23.14981943252</font>
cost per epoch: $ <font color="#C4A000">69.46763698028</font>
cost per day if epoch = 10min: $ <font color="#C4A000">10003.33972516032</font>
cost per week if epoch = 10min: $ <font color="#C4A000">70023.37807612224</font>
cost per month if epoch = 10min: $ <font color="#C4A000">300100.1917548096</font>
cost per day if epoch = 1 hour: $ <font color="#C4A000">1667.22328752672</font>
cost per week if epoch = 1 hour: $ <font color="#C4A000">11670.56301268704</font>
cost per month if epoch = 1 hour: $ <font color="#C4A000">50016.6986258016</font>
========================================================
On Polygon network. It will take take following cost for tx
Commit: $ <font color="#C4A000">0.0005178109278</font>
reveal: $ <font color="#C4A000">0.000826292988</font>
propose: $ <font color="#C4A000">0.0005174046294000001</font>
cost per epoch: $ <font color="#C4A000">0.0015526201866</font>
cost per day if epoch = 10min: $ <font color="#C4A000">0.22357730687039998</font>
cost per week if epoch = 10min: $ <font color="#C4A000">1.5650411480928</font>
cost per month if epoch = 10min: $ <font color="#C4A000">6.7073192061119995</font>
cost per day if epoch = 1 hour: $ <font color="#C4A000">0.037262884478399996</font>
cost per week if epoch = 1 hour: $ <font color="#C4A000">0.2608401913488</font>
cost per month if epoch = 1 hour: $ <font color="#C4A000">1.117886534352</font>
On Arbitrum network. It will take take following cost for tx (Not real time)
Commit: $ <font color="#C4A000">0.2369454352695</font>
reveal: $ <font color="#C4A000">0.37810393947000004</font>
propose: $ <font color="#C4A000">0.2367595169235</font>
cost per epoch: $ <font color="#C4A000">0.7104644691165001</font>
cost per day if epoch = 10min: $ <font color="#C4A000">102.306883552776</font>
cost per week if epoch = 10min: $ <font color="#C4A000">716.148184869432</font>
cost per month if epoch = 10min: $ <font color="#C4A000">3069.20650658328</font>
cost per day if epoch = 1 hour: $ <font color="#C4A000">17.051147258796</font>
cost per week if epoch = 1 hour: $ <font color="#C4A000">119.35803081157201</font>
cost per month if epoch = 1 hour: $ <font color="#C4A000">511.53441776388</font>
========================================================
On Avalanche network. It will take take following cost for tx
Commit: $ <font color="#C4A000">1.75973696325</font>
reveal: $ <font color="#C4A000">2.808087345</font>
propose: $ <font color="#C4A000">1.75835619225</font>
cost per epoch: $ <font color="#C4A000">5.27644934775</font>
cost per day if epoch = 10min: $ <font color="#C4A000">759.808706076</font>
cost per week if epoch = 10min: $ <font color="#C4A000">5318.660942532</font>
cost per month if epoch = 10min: $ <font color="#C4A000">22794.26118228</font>
cost per day if epoch = 1 hour: $ <font color="#C4A000">126.634784346</font>
cost per week if epoch = 1 hour: $ <font color="#C4A000">886.443490422</font>
cost per month if epoch = 1 hour: $ <font color="#C4A000">3799.04353038</font>
========================================================
On xDAI network. It will take take following cost for tx (Not real time)
Commit: $ <font color="#C4A000">0.000158033</font>
reveal: $ <font color="#C4A000">0.00025218</font>
propose: $ <font color="#C4A000">0.000157909</font>
cost per epoch: $ <font color="#C4A000">0.00047385099999999996</font>
cost per day if epoch = 10min: $ <font color="#C4A000">0.068234544</font>
cost per week if epoch = 10min: $ <font color="#C4A000">0.47764180799999995</font>
cost per month if epoch = 10min: $ <font color="#C4A000">2 [...]

2021-08-23 07:37 UTC, SkandaBhat commented on contracts/Core/Parameters.sol
> +        uint8 state = uint8(((block.number) / (epochLength / NUM_STATES)) % (NUM_STATES));
I see.

2021-08-23 07:38 UTC, SkandaBhat commented on contracts/Core/AssetManager.sol
> +    //event CollectionReported(
Better to remove instead of comment as a thumb rule since even removal diff is stored in git history.

2021-08-23 14:18 UTC, hrishikeshio commented
> > Please add gas usage report. before and after.
> 
> @hrishikeshio @abhishekvispute @SkandaBhat
> After
> 
> On ethereum network. It will take take following cost for tx
> Commit: $ 21.95524854768
> reveal: $ 34.9343652504
> propose: $ 22.4826230328
> cost per epoch: $ 66.92049461328
> cost per day if epoch = 10min: $ 9636.55122431232
> cost per week if epoch = 10min: $ 67455.85857018623
> cost per month if epoch = 10min: $ 289096.5367293696
> cost per day if epoch = 1 hour: $ 1606.09187071872
> cost per week if epoch = 1 hour: $ 11242.64309503104
> cost per month if epoch = 1 hour: $ 48182.7561215616
> ========================================================
> On Polygon network. It will take take following cost for tx
> Commit: $ 0.0003944551659025628
> reveal: $ 0.000627642215510395
> propose: $ 0.0004039301481405922
> cost per epoch: $ 0.0012023154621837472
> cost per day if epoch = 10min: $ 0.1731334265544596
> cost per week if epoch = 10min: $ 1.2119339858812173
> cost per month if epoch = 10min: $ 5.194002796633788
> cost per day if epoch = 1 hour: $ 0.028855571092409934
> cost per week if epoch = 1 hour: $ 0.20198899764686953
> cost per month if epoch = 1 hour: $ 0.865667132772298
> On Arbitrum network. It will take take following cost for tx (Not real time)
> Commit: $ 0.235234805868
> reveal: $ 0.37429677054000005
> propose: $ 0.24088524678
> cost per epoch: $ 0.7170052994280001
> cost per day if epoch = 10min: $ 103.24876311763201
> cost per week if epoch = 10min: $ 722.741341823424
> cost per month if epoch = 10min: $ 3097.46289352896
> cost per day if epoch = 1 hour: $ 17.208127186272
> cost per week if epoch = 1 hour: $ 120.456890303904
> cost per month if epoch = 1 hour: $ 516.24381558816
> ========================================================
> On Avalanche network. It will take take following cost for tx
> Commit: $ 1.74860171325
> reveal: $ 2.78230924125
> propose: $ 1.79060387625
> cost per epoch: $ 5.3298094657499995
> cost per day if epoch = 10min: $ 767.492563068
> cost per week if epoch = 10min: $ 5372.447941476
> cost per month if epoch = 10min: $ 23024.776892039998
> cost per day if epoch = 1 hour: $ 127.91542717799999
> cost per week if epoch = 1 hour: $ 895.4079902459999
> cost per month if epoch = 1 hour: $ 3837.4628153399995
> ========================================================
> On xDAI network. It will take take following cost for tx (Not real time)
> Commit: $ 0.000157033
> reveal: $ 0.000249865
> propose: $ 0.000160805
> cost per epoch: $ 0.00047864299999999995
> cost per day if epoch = 10min: $ 0.06892459199999999
> cost per week if epoch = 10min: $ 0.48247214399999994
> cost per month if epoch = 10min: $ 2.06773776
> cost per day if epoch = 1 hour: $ 0.011487431999999999
> cost per week if epoch = 1 hour: $ 0.080412024
> cost per month if epoch = 1 hour: $ 0.34462296
> Before
> 
> On ethereum network. It will take take following cost for tx
> Commit: $ 23.167998115240003
> reveal: $ 36.970162970400004
> propose: $ 23.14981943252
> cost per epoch: $ 69.46763698028
> cost per day if epoch = 10min: $ 10003.33972516032
> cost per week if epoch = 10min: $ 70023.37807612224
> cost per month if epoch = 10min: $ 300100.1917548096
> cost per day if epoch = 1 hour: $ 1667.22328752672
> cost per week if epoch = 1 hour: $ 11670.56301268704
> cost per month if epoch = 1 hour: $ 50016.6986258016
> ========================================================
> On Polygon network. It will take take following cost for tx
> Commit: $ 0.0005178109278
> reveal: $ 0.000826292988
> propose: $ 0.0005174046294000001
> cost per epoch: $ 0.0015526201866
> cost per day if epoch = 10min: $ 0.22357730687039998
> cost per week if epoch = 10min: $ 1.5650411480928
> cost per month if epoch = 10min: $ 6.7073192061119995
> cost per day if epoch = 1 hour: $ 0.037262884478399996
> cost per week if epoch = 1 hour: $ 0.2608401913488
> cost per month if epoch = 1 hour: $ 1.117886534352
> On Arbitrum network. It will take take following cost for tx (Not real time)
> Commit: $ 0.2369454352695
> reveal: $ 0.37810393947000004
> propose: $ 0.2367595169235
> cost per epoch: $ 0.7104644691165001
> cost per day if epoch = 10min: $ 102.306883552776
> cost per week if epoch = 10min: $ 716.148184869432
> cost per month if epoch = 10min: $ 3069.20650658328
> cost per day if epoch = 1 hour: $ 17.051147258796
> cost per week if epoch = 1 hour: $ 119.35803081157201
> cost per month if epoch = 1 hour: $ 511.53441776388
> ========================================================
> On Avalanche network. It will take take following cost for tx
> Commit: $ 1.75973696325
> reveal: $ 2.808087345
> propose: $ 1.75835619225
> cost per epoch: $ 5.27644934775
> cost per day if epoch = 10min: $ 759.808706076
> cost per week if epoch = 10min: $ 5318.660942532
> cost per month if epoch = 10min: $ 22794.26118228
> cost per day if epoch = 1 hour: $ 126.634784346
> cost per week if epoch = 1 hour: $ 886.443490422
> cost per month if epoch = 1 hour: $ 3799.04353038
> ========================================================
> On xDAI network. It will take take following cost for tx (Not real time)
> Commit: $ 0.000158033
> reveal: $ 0.00025218
> propose: $ 0.000157909
> cost per epoch: $ 0.00047385099999999996
> cost per day if epoch = 10min: $ 0.068234544
> cost per week if epoch = 10min: $ 0.47764180799999995
> cost per month if epoch = 10min: $ 2.0470363199999997
> cost per day if epoch = 1 hour: $ 0.011372423999999999
> cost per week if epoch = 1 hour: $ 0.079606968
> cost per month if epoch = 1 hour: $ 0.34117272

eth gas reporter analysis not this one.

this one is not static. its different depending on when you run it.

2021-08-24 08:12 UTC, SamAg19 commented
@hrishikeshio @abhishekvispute @SkandaBhat

Before

<pre>·-----------------------------------------------|---------------------------|----------------|-----------------------------·
|              Solc version: 0.8.4              ·  Optimizer enabled: true  ·  Runs: 100000  ·  Block limit: 12450000 gas  │
················································|···························|················|······························
|  Methods                                                                                                                 │
··················|·····························|·············|·············|················|···············|··············
|  Contract       ·  Method                     ·  Min        ·  Max        ·  Avg           ·  # calls      ·  usd (avg)  │
··················|·····························|·············|·············|················|···············|··············
|  AssetManager   ·  addJobToCollection         ·          -  ·          -  ·         77732  ·            2  ·          -  │
··················|·····························|·············|·············|················|···············|··············
|  AssetManager   ·  createCollection           ·     209853  ·     209997  ·        209901  ·            6  ·          -  │
··················|·····························|·············|·············|················|···············|··············
|  AssetManager   ·  createJob                  ·     134095  ·     134479  ·        134141  ·           16  ·          -  │
··················|·····························|·············|·············|················|···············|··············
|  AssetManager   ·  grantRole                  ·      51251  ·      51275  ·         51273  ·           60  ·          -  │
··················|·····························|·············|·············|················|···············|··············
|  AssetManager   ·  removeJobFromCollection    ·      52531  ·      54448  ·         53490  ·            2  ·          -  │
··················|·····························|·············|·············|················|···············|··············
|  AssetManager   ·  revokeRole                 ·          -  ·          -  ·         19135  ·            7  ·          -  │
··················|·····························|·············|·············|················|···············|··············
|  AssetManager   ·  setAssetStatus             ·      36470  ·      41271  ·         39565  ·            8  ·          -  │
··················|·····························|·············|·············|················|···············|··············
|  AssetManager   ·  updateCollection           ·      49775  ·      49828  ·         49802  ·            2  ·          -  │
··················|·····························|·············|·············|················|···············|··············
|  AssetManager   ·  updateJob                  ·          -  ·          -  ·         58190  ·            2  ·          -  │
··················|·····························|·············|·············|················|···············|··············
|  BlockManager   ·  claimBlockReward           ·     183675  ·     223475  ·        213525  ·            6  ·          -  │
··················|·····························|·············|·············|················|···············|··············
|  BlockManager   ·  confirmPreviousEpochBlock  ·          -  ·          -  ·         35969  ·            1  ·          -  │
··················|·····························|·············|·············|················|···············|··············
|  BlockManager   ·  finalizeDispute            ·      78612  ·     130712  ·         97337  ·            4  ·          -  │
··················|·····························|·············|·············|················|···············|··············
|  BlockManager   ·  giveSorted                 ·      60225  ·     163172  ·        119448  ·            8  ·          -  │
··················|·····························|·············|·············|················|···············|··············
|  BlockManager   ·  grantRole                  ·      51301  ·      51313  ·         51313  ·           35  ·          -  │
··················|·····························|·············|·············|················|···············|··············
|  BlockManager   ·  initialize                 ·     159351  ·     159363  ·        159352  ·           31  ·          -  │
··················|·····························|·············|·············|················|···············|··············
|  BlockManager   ·  propose                    ·     216338  ·     266627  ·        243161  ·           13  ·          -  │
··················|·····························|·············|·············|················|···············|··············
|  BlockManager   ·  resetDispute               ·          -  ·          -  ·         23579  ·            1  ·          -  │
··················|·····························|·············|·············|················|···············|··············
|  BlockManager   ·  revokeRole                 ·          -  ·          -  ·         19221  ·            1  ·          -  │
··················|·····························|·············|·············|················|···············|··············
|  Delegator      ·  upgradeDelegate            ·      34098  ·      68310  ·         67230  ·           32  ·          -  │
··················|·····························|·············|·············|················|···············|··············
|  Parameters     ·  disableEscapeHatch         ·          -  ·          -  ·         16299  ·            1  ·          -  │
··················|·····························|·············|·············|················|···············|··············
|  Parameters     ·  setAggregationRange        ·          -  ·          -  ·         31715  ·            1  ·          -  │
··················|·····························|·············|·············|················|···············|··············
|  Parameters     ·  setBlockReward             ·          -  ·          -  ·         28833  ·            1  ·          -  │
··················|·····························|·············|·············|················|···············|··············
|  Parameters     ·  setEpochLength             ·          -  ·          -  ·         31738  ·            1  ·          -  │
··················|·····························|·············|·············|················|···············|··············
|  Parameters     ·  setExposureDenominator     ·          -  ·          -  ·         31715  ·            1  ·          -  │
··················|·····························|·············|·············|················|···············|··············
|  Parameters     ·  setGracePeriod             ·          -  ·          -  ·         31737  ·            1  ·          -  │
··················|·····························|·············|·············|················|···············|··············
|  Parameters     ·  setMaxAge                  ·          -  ·          -  ·         31760  ·            1  ·          -  │
··················|·····························|·············|·············|················|···············|··············
|  Parameters     ·  setMaxAltBlocks            ·          -  ·          -  ·         31760  ·            1  ·          -  │
··················|·····························|·············|·············|················|···············|··············
|  Parameters     ·  setMinStake                ·      16503  ·      31515  ·         24009  ·            2  ·          -  │
··················|·····························|·············|·············|················|···············|··············
|  Parameters     ·  setPenaltyNotRevealDeom    ·          -  ·      [...]

2021-08-24 11:44 UTC, SkandaBhat approved these changes
Looks good to me.

2021-08-25 03:05 UTC, abhishekvispute approved these changes

2021-08-25 07:57 UTC, merged