Job selector implemented.
razor-network/contracts pull request #382
Opened 2021-08-31 11:05 UTC by ashish10677

A new parameter has been added while creating a job (`selectorType`).

Made changes to all the tests.

Closes #310

2021-08-31 11:07 UTC, hrishikeshio commented on contracts/Core/AssetManager.sol
> +        uint8 selectorType,
Using enum can make it more readable.

2021-08-31 12:39 UTC, ashish10677 commented
Will be fixing the VoteManager tests in the next commit.

2021-09-02 08:15 UTC, SkandaBhat requested changes
Please change number to enum for readability.

2021-09-06 12:20 UTC, SkandaBhat approved these changes
Looks good to me.

2021-09-06 15:32 UTC, hrishikeshio commented
@abhishekvispute Can you check if variablesa re tightly packed?

2021-09-06 16:56 UTC, abhishekvispute commented
> @abhishekvispute Can you check if variables are tightly packed?

sure

2021-09-06 17:10 UTC, abhishekvispute commented
> @abhishekvispute Can you check if variables are tightly packed?

Yep they are 
As the number of members is 2 in this enum, it will be converted to uint8 so 
```
 event JobCreated(
        uint8 id,
        JobSelectorType selectorType,
        int8 power,
        address creator, 
        uint32 epoch, 1 slot
        uint256 timestamp, 1 slot
        string name,
        string selector,
        string url
    );
```
```
 event JobUpdated(
 uint8 id, 
 JobSelectorType selectorType, 
 uint32 epoch, 
 int8 power, 1 slot
 uint256 timestamp, 1 slot
 string selector, string URL);
 ```
```
 struct Job {
        bool active;
        uint8 id;
        uint8 assetType;
        uint8 selectorType;
        int8 power;
        uint32 epoch;
        address creator; 1 slot
        string name;
        string selector;
        string url;
    }
```

2021-09-06 17:12 UTC, abhishekvispute approved these changes

2021-09-06 18:41 UTC, merged