Checked for penalties is being given out correctly when previous epoch block is being confirmed
razor-network/contracts pull request #470
Opened 2021-09-27 12:01 UTC by GauravJain9

Fixes #458

2021-09-30 11:03 UTC, abhishekvispute submitted a review, later dismissed

2021-09-30 11:18 UTC, SamAg19 submitted a review, later dismissed

2021-10-01 09:05 UTC, hrishikeshio requested changes

2021-10-01 11:22 UTC, GauravJain9 commented on test/BlockManager.js
> +      const newStake = (prevStake.add(reward)).sub(randaoPenalty);
Yeah, but in issue we just want to validate that if the block of previous epoch is being confirmed and at the same time  penalty is being applied so in this scenario it should be applied correctly just the validation.

2021-10-01 11:57 UTC, adi44 commented on test/BlockManager.js
> +      const newStake = (prevStake.add(reward)).sub(randaoPenalty);
No actually we want to check if block is not confirmed in comfirm state, then in commit state block should get confirmed first and then penalties should be applied. I think you can calculate penalties off chain when block is confirmed before applying penalties and then assert it with the penalties applied to staker.

2021-10-01 13:08 UTC, abhishekvispute commented on test/BlockManager.js
> +      const newStake = (prevStake.add(reward)).sub(randaoPenalty);
As dis 
separate confirmer with rando one
and please have check for age penalty as well, for may votes by staker

2021-10-04 07:51 UTC, hrishikeshio approved these changes

2021-10-04 07:52 UTC, SkandaBhat approved these changes

2021-10-04 08:01 UTC, merged