Configure ci
razor-network/contracts pull request #627
Opened 2021-12-21 17:44 UTC by Shrikant1212

2021-12-22 09:32 UTC, SkandaBhat requested changes

2021-12-22 09:32 UTC, SkandaBhat commented on .circleci/config.yml
> +  publish-package:
Cannot see this job being called anywhere.

2021-12-22 17:42 UTC, adi44 commented on .circleci/config.yml
> +            git config user.email "shrikant1997upadhyay@gmail.com"
Yes I have created one for gascompare

2022-01-05 13:04 UTC, SkandaBhat commented
@Shrikant1212 any updates here?

2022-01-07 12:58 UTC, SkandaBhat commented
Closing this. Please open when ready to merge @Shrikant1212

2022-01-07 12:58 UTC, closed without merging