bounty id now emitted
razor-network/contracts pull request #680
Opened 2022-02-05 09:49 UTC by SamAg19

fixes #671

2022-02-07 06:43 UTC, SkandaBhat requested changes
Please fix lint errors.

2022-02-07 07:05 UTC, SamAg19 commented
> Please fix lint errors.

Done https://github.com/razor-network/contracts/pull/680/commits/c42da683a607ceb903074efa5e5501e6ad62ed50

2022-02-07 09:07 UTC, abhishekvispute approved these changes

2022-02-09 07:59 UTC, SkandaBhat approved these changes

2022-02-09 07:59 UTC, merged