Safe age limit and required added
razor-network/contracts pull request #694
Opened 2022-02-10 12:56 UTC by SamAg19

fixes #688

2022-02-10 13:20 UTC, abhishekvispute approved these changes

2022-02-14 05:48 UTC, SkandaBhat commented on contracts/Core/parameters/Governance.sol
> +        require(_maxAge <= 100 * 10000, "Invalid Max Age Update");
Does it make sense to assign this to say `maxSafeAge`? We may end up forgetting about this require if we change the age mapping.

2022-02-14 10:17 UTC, SkandaBhat requested changes

2022-02-17 07:39 UTC, abhishekvispute approved these changes

2022-02-17 21:26 UTC, hrishikeshio approved these changes

2022-02-17 21:27 UTC, merged