test: increased coverage on BlockManager and RandomNoManager
razor-network/contracts pull request #733
Opened 2022-02-28 06:44 UTC by GauravJain9

2022-02-28 07:07 UTC, SamAg19 requested changes
coverage of block manager is not 100%. Please increase the coverage for block manager

2022-02-28 09:27 UTC, GauravJain9 commented
> coverage of block manager is not 100%. Please increase the coverage for block manager

Checks left may not be reached so can have discussion to not delay decided to push this

2022-03-08 09:49 UTC, SamAg19 approved these changes

2022-03-08 22:19 UTC, abhishekvispute approved these changes

2022-03-09 07:41 UTC, merged